services:
  - type: web
    name: autoprint-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://misbah244176_db_user:QcAQFTCziOs43vR2@autoprint.karym06.mongodb.net/autoprint
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /api/health